### ISSUE TITLE
Недочеты сайта

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#26]
1. Для слайдера не работают touch события (он не доступен для мобильных устройств)

https://user-images.githubusercontent.com/75975369/115101485-3840c880-9f4d-11eb-90d7-5e077834c3f0.mp4

2. `Войти` и `Зарегистрироваться` должны быть ссылками

https://user-images.githubusercontent.com/75975369/115101567-fbc19c80-9f4d-11eb-823e-2a583326bfed.mp4

3. Dropdown. Кнопка `применить` не работает. Логичное поведение в данном случае закрывать дродаун и вызывть callback с результатом изменений содержимого дропдауна.

https://user-images.githubusercontent.com/75975369/115101617-607cf700-9f4e-11eb-9ca3-9b8e77d1b8cc.mp4

4. Небольшое несоответствие макету (дата должна быть в одну строчку)

![maket](https://user-images.githubusercontent.com/75975369/115101754-717a3800-9f4f-11eb-864b-291e1cb91d04.jpg)

5. Вот в этой галерее у тебя фиксированная высота и при разных разрешениях получается, что части картинок не видны. Давай переделаем так, что бы пропорции картинок не менялись и они при разных разрешениях были видны целиком.

https://user-images.githubusercontent.com/75975369/115101935-8d320e00-9f50-11eb-8b72-c51b5bfda02a.mp4

**Comment by mglknFSD** [comment]
6.  Социальные иконки, в качестве заглушки, должны вести на соответствующие сайты.

**Comment by Rqik** [comment]
1. Убрал Jqslider. Подключил ionRangeSlider, перенастроил заново и переписал стили под него.
2. Сделал ссылки на страницы Регистрации и Авторизации 
3. Добавил событие скрытия на кнопку submit в dropdown 
4. Исправил макет
5. Изменил верстку в галерее. Долго думал и искал как сделать так чтобы grid сетка брала за высоту минимальную высоту контента. Так ничего толкового и не нашел. Js подключать не хотел для этого. Поэтому сделал что-то среднее между grid и flex 
6. Добавил ссылки и alt на соцсети

**Comment by mglknFSD** [comment]
![center](https://user-images.githubusercontent.com/75975369/115954209-5a5fbb00-a4f8-11eb-8279-d51249d0a01c.jpg)

Бегунки немного не по центру.

**Comment by mglknFSD** [comment]
![margin](https://user-images.githubusercontent.com/75975369/115954304-dbb74d80-a4f8-11eb-8a5c-df2608030315.jpg)

Отступ не как на макете.

**Comment by mglknFSD** [comment]
Тень не как на макете

![shadow](https://user-images.githubusercontent.com/75975369/115954338-18834480-a4f9-11eb-94d6-2bb5d7bb68e8.jpg)

**Comment by Rqik** [comment]
![image](https://user-images.githubusercontent.com/47545695/116095445-16fc7c80-a6b1-11eb-9620-8de525128146.png)
Ровнее сделать ближе сделать не получается левый ползунок. Перестает правильно выполнять расчеты. Пытался встроенными методами изменить при Change событии не работает. Как вариант еще раз менять плагин...
