### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#27]
1. favicon не отображается в firefox

![favicon](https://user-images.githubusercontent.com/75975369/115102135-c323c200-9f51-11eb-8c5b-ea884729ad9f.jpg)

2. favicon должен иметь возможность подключаться на каждой странице
3. favicon для safari не настроен

**Comment by Rqik** [comment]
![image](https://user-images.githubusercontent.com/47545695/115262862-93391200-a13d-11eb-99b9-4a88db74ac62.png)

**Comment by Rqik** [comment]
1. У меня работало
2. Добавил возможность переопределить Favicon на каждой странице
3. 
![image](https://user-images.githubusercontent.com/47545695/115269969-853abf80-a144-11eb-8999-90bded82fa97.png)
На сафари через онлайн сервис проверил показывает. Правда остальная верстка летит
