### ISSUE TITLE
images

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#28]
1. Картинки не оптимизированы (смотри 'бест практис')
2. Все svg надо пропустить через [svgo](https://jakearchibald.github.io/svgomg/)
3. Необходимо по максимуму использовать svg где это возможно
4. Картинки носящие декоративный характер, т е проде не предполагается, что ссылки на них будут приходить из какого-то аpi (например картинки галлереи), хранить необходимо в самих компонентах.

**Comment by Rqik** [comment]
1.Оптимизировал картинки.
2.Пропустил svg через svgo
3.Заменил логотипы с png на svg. Иконку чекбокса не смог настроить я и до этого пытался сделать чтобы он был svg. Но он тупо не считывается хз как с этим бороться оставил png.
4.Перенес фоновые картинки по папкам страниц
Перехожу к исправлению в слайдере

**Comment by mglknFSD** [comment]
> Заменил логотипы с png на svg. Иконку чекбокса не смог настроить я и до этого пытался сделать чтобы он был svg. Но он тупо не считывается хз как с этим бороться оставил png.

Мне не очень понятно что значит "не считывается". Для таких элементов как чекбокс иконки должны быть svg. Реши пожалуйста проблему.

**Comment by mglknFSD** [comment]
![images](https://user-images.githubusercontent.com/75975369/115954595-8714d200-a4fa-11eb-86e5-15bd277e2258.jpg)

Картинки носящие декоративный характер, т е проде не предполагается, что ссылки на них будут приходить из какого-то аpi (например картинки галлереи), хранить необходимо в самих компонентах.

**Comment by Rqik** [comment]
Исправил. 
1. Svg не считывались потому-что в webpack file-loader и svg-inline-loader конфликтовали и переписывали друг друга. Последний как оказалось еще не поддерживается больше разработчиком. Заменил на svg-url-loader. 
2.Импортировать svg в pug mixin оказалось еще большей проблемой requier не получилось, пробовал разными способами, пришел к тому что просто includ-ом добавил

**Comment by Rqik** [comment]
> ![images](https://user-images.githubusercontent.com/75975369/115954595-8714d200-a4fa-11eb-86e5-15bd277e2258.jpg)
> 
> Картинки носящие декоративный характер, т е проде не предполагается, что ссылки на них будут приходить из какого-то аpi (например картинки галлереи), хранить необходимо в самих компонентах.

**Comment by Rqik** [comment]
Логотип токсина оставил в assets это же не ошибка?
