### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#29]
1. В аргументах функций ты делаешь нечто странное. Ты берешь значение по умолчанию как пустой объект, и пытаешься из него извлечь данные. Для чего?
2. Тут и в других местах. `title1` и `title2` - плохое именование. Следует давать всем переменным осмысленные имена.

![pug](https://user-images.githubusercontent.com/75975369/115102627-c3718c80-9f54-11eb-8bd7-acfc45a2e731.jpg)

3. Очевидно, что тут опечатка (в макете). Но нужно писать правильно. 
![typo](https://user-images.githubusercontent.com/75975369/115102751-aab5a680-9f55-11eb-8623-8fc99517f536.jpg)

4. Форматирование. Длинные строки очень неудобно читать. У нас по стандарту airbnb максимальная длинна строк 80 символов, давай будем ориентироваться на этот стандарт.

![long_string](https://user-images.githubusercontent.com/75975369/115102961-f157d080-9f56-11eb-9fbc-c737cbf24b8e.jpg)

**Comment by Rqik** [comment]
1. Смотрел примеры деструктуризации в pug и там задавали дефолтное значение переменной в виде объекта, а потом его деструктурировали.
2. Исправил наименование title1, title2 на firstTitle, secondTitle и в cardRoom вместо room на roomNumber.
3. Исправил опечатку
4. Сделал перенос строк где длинна больше 80 символов

**Comment by mglknFSD** [comment]
> 
> 
>     1. Смотрел примеры деструктуризации в pug и там задавали дефолтное значение переменной в виде объекта, а потом его деструктурировали.
> 
>     2. Исправил наименование title1, title2 на firstTitle, secondTitle и в cardRoom вместо room на roomNumber.
> 
>     3. Исправил опечатку
> 
>     4. Сделал перенос строк где длинна больше 80 символов

1 - примеры, это конечно, хорошо, но вопрос был "для чего?" В чем смысл так делать?

**Comment by Rqik** [comment]
Я сам не особо понимаю для чего. Предположу что для того, чтобы было ясно что mixin принимает объект porps. Что-то похожее на typescript.... Везде удалил это дополнение

**Comment by mglknFSD** [comment]
Тут и проверь весь проект - теги без класса запрещены

![div](https://user-images.githubusercontent.com/75975369/115954723-32258b80-a4fb-11eb-92a9-08a0545e1360.jpg)

**Comment by mglknFSD** [comment]
Для js по нашим бест практис следует использовать одинарные кавычки. js в pug не является исключением.

![js](https://user-images.githubusercontent.com/75975369/115954819-aeb86a00-a4fb-11eb-8fa5-48452989e323.jpg)

**Comment by Rqik** [comment]
Вопрос. Если плагин требует такую структуру.
![image](https://user-images.githubusercontent.com/47545695/116034398-e0e8d980-a66b-11eb-8dce-95caae2cb8bd.png)
Мне можно его в таком виде оставить? Но как отдельный компонент
