### ISSUE TITLE
css

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#30]
1. Форматирование. Для всего проекта необходимо выбрать либо 2 либо 4 пробела для отступа. У тебя тут 4 в другом коде 
![trash](https://user-images.githubusercontent.com/75975369/115103274-4eed1c80-9f59-11eb-8f7f-6715523decd9.jpg)

![formatting](https://user-images.githubusercontent.com/75975369/115103065-8c50aa80-9f57-11eb-91b9-bc2635c31bfa.jpg)

2. Шрифты то же удобно занести в переменные.

3. Assets это папка для скомпилированных стилей, шрифтов, картинок и т. д. Код с которым ты работаешь (то что ты редактируешь) не должно лежать в папке assets.
![assets](https://user-images.githubusercontent.com/75975369/115103126-2add0b80-9f58-11eb-9659-e3c8c9b22eb9.jpg)
 
4. Отрицательный margin запрещен. Тут и в других местах.
![negate margin](https://user-images.githubusercontent.com/75975369/115103166-91622980-9f58-11eb-84b4-edb67d576f33.jpg)

5. В коде не должно быть мусора (закоментированного кода)
![trash](https://user-images.githubusercontent.com/75975369/115103289-60cebf80-9f59-11eb-9524-a3a6da1b63f4.jpg)

6. Глобальные стили не допустимы. Допустимы только для тегов body, html и для переопределения box-sizing для всех тегов.
![globlstyle](https://user-images.githubusercontent.com/75975369/115103343-ece0e700-9f59-11eb-9255-91f5b61bfede.jpg)
![globlstyle](https://user-images.githubusercontent.com/75975369/115103359-fe29f380-9f59-11eb-9b05-31e19dc5c62a.jpg)

**Comment by Rqik** [comment]
Исправил ошибку в форматировании fonts, вынес размеры шрифтов в переменные, создал для material-coins отдельный блок компонент, вынес из assets css в новую папку styles, удалил отрицательные margin, убрал закомментированный код, глобальные стили перенес по компонентам

**Comment by Rqik** [comment]
Исправил ошибку в форматировании fonts, вынес размеры шрифтов в переменные, создал для material-coins отдельный блок компонент, вынес из assets css в новую папку styles, удалил отрицательные margin, убрал закомментированный код, глобальные стили перенес по компонентам

**Comment by mglknFSD** [comment]
Для шрифтов удобно завести переменные.

![fonts](https://user-images.githubusercontent.com/75975369/115954891-1bcbff80-a4fc-11eb-8e3a-aee48d61ab41.jpg)

**Comment by mglknFSD** [comment]
Крайне неудачное название переменной. Если ты хотел сделать прозрачные бордер, то для прозрачного цвета есть ключевое слово `transparent`. С другой стороны зачем делать прозрачный бордер? Но из названия переменной он должен быть именно таким... 

![transparent](https://user-images.githubusercontent.com/75975369/115954950-6e0d2080-a4fc-11eb-935f-70057a83f030.jpg)

**Comment by mglknFSD** [comment]
Медиа запросы необходимо указывать "внутри" каждого из классов для которого мы хотим добавить "медиа стили". Для того чтобы можно было легко отследить как конкретный медиа запарос влияет на конкретный класс.

![media](https://user-images.githubusercontent.com/75975369/115955146-a103e400-a4fd-11eb-93c1-a22d9bfcb6fd.jpg)

**Comment by mglknFSD** [comment]
Именование модификаторов. Тут и по всему проекту. Как правильно это делать можно прочитать [тут](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![modificators](https://user-images.githubusercontent.com/75975369/115955300-55056f00-a4fe-11eb-9a89-7c5629477e1c.jpg)

**Comment by mglknFSD** [comment]
БЭМ. Для каждого блока должен быть свой отдельный "стилевой неймспейс". Нельзя вот так смешивать разные классы.

![bem](https://user-images.githubusercontent.com/75975369/115955461-30f65d80-a4ff-11eb-83d3-ca5d13277f8b.jpg)

**Comment by Rqik** [comment]
Исправил

**Comment by mglknFSD** [comment]
Не стоит смешивать rem и px. Лучше использовать что-то одно. 

![rem](https://user-images.githubusercontent.com/75975369/116789026-798cb880-aab5-11eb-97cd-0aa8e937ab96.jpg)

**Comment by mglknFSD** [comment]
Посторонний класс внутри блока

![css](https://user-images.githubusercontent.com/75975369/116789231-82ca5500-aab6-11eb-98d8-afff25192069.jpg)

**Comment by mglknFSD** [comment]
Для чего писать префиксы? У тебя же стоит autoprefixer...

![prefixes](https://user-images.githubusercontent.com/75975369/116789306-e5235580-aab6-11eb-92e9-6f3e5703d9dd.jpg)

**Comment by mglknFSD** [comment]
Не понятные имена модификаторов. 

![modificators](https://user-images.githubusercontent.com/75975369/116789431-6bd83280-aab7-11eb-97b5-b954ef91431d.jpg)

Имена модификаторов не соответсвуют [best practice](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![modif](https://user-images.githubusercontent.com/75975369/116789456-8dd1b500-aab7-11eb-963e-7c01f514b688.jpg)

**Comment by Rqik** [comment]
> Для чего писать префиксы? У тебя же стоит autoprefixer...
> 
> ![prefixes](https://user-images.githubusercontent.com/75975369/116789306-e5235580-aab6-11eb-92e9-6f3e5703d9dd.jpg)

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color 
-webkit-text-fill-color не является стандартизированным поэтому не поддерживается autoprefixer-ом

**Comment by Rqik** [comment]
![image](https://user-images.githubusercontent.com/47545695/116861074-35133100-ac0b-11eb-87b4-58db41c07355.png)
такое наименование модификатора допустимо?

**Comment by mglknFSD** [comment]
Пустой селектор

![empty](https://user-images.githubusercontent.com/75975369/117542852-0c33d700-b023-11eb-8ff0-aad7cb91827a.jpg)

**Comment by mglknFSD** [comment]
Именование. Если ты называешь блок register то и имя компонента должно быть такое же. Это упрощает поиск по проекту.

![naming](https://user-images.githubusercontent.com/75975369/117542958-67fe6000-b023-11eb-94ae-77f7dd90e9c9.jpg)

**Comment by mglknFSD** [comment]
Именование. Если ты называешь блок register то и имя компонента должно быть такое же. Это упрощает поиск по проекту.
![wrapper](https://user-images.githubusercontent.com/75975369/117700966-59ed4280-b1cf-11eb-816d-55f28a0fdc9d.jpg)
