### ISSUE TITLE
js

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#31]
1. Обработчики событий необходимо выноситьв отдельный метод

![handlers](https://user-images.githubusercontent.com/75975369/115103751-059ecc00-9f5d-11eb-9fe5-f67ce7e9e0a5.jpg)

2. Неиспользуемые пеменные - заменять на undescore или помечать underscore
3. Именование переменных должно быть осмысленным (я не смог понять что такое `fd`)
![unused vars](https://user-images.githubusercontent.com/75975369/115103792-4696e080-9f5d-11eb-981c-739641d2a3fb.jpg)

4. Где возможно следует использовать деструктуризацию
![Screenshot_1](https://user-images.githubusercontent.com/75975369/115104106-06d0f880-9f5f-11eb-93c3-1ddb77ebdef5.jpg)

5. Именование файлов. pages это по сути те же компоненты и устроены они должны быть единообразно т е если опираться на то как устроены компоненты, инициализация должна происходить в index.js, бизнес логика - в классах.
![struct](https://user-images.githubusercontent.com/75975369/115104199-852d9a80-9f5f-11eb-9389-44bd5cdbc0f8.jpg)

**Comment by Rqik** [comment]
![image](https://user-images.githubusercontent.com/47545695/115167957-0604a780-a0c2-11eb-9876-07f3912c617f.png)
Я могу передать вызов метода в событие, таким образом? Мне в методе селектор нужен, а сам Event нет.

**Comment by mglknFSD** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/47545695/115167957-0604a780-a0c2-11eb-9876-07f3912c617f.png)
> Я могу передать вызов метода в событие, таким образом? Мне в методе селектор нужен, а сам Event нет.

[Best practice](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.13)

**Comment by Rqik** [comment]
1. Вынес все обработчики событий в методы. Использовал hoc функции, там где нельзя было обойтись без них. Использовал сам event вместо this. 
3. Исправил. Fd это в самой документации к airdatepicker автор так использовал  formattedDate
4. Деструктурировал  эту переменную на year, month, day. В других местах пока не находил
5. Исправил логику в страницах

**Comment by mglknFSD** [comment]
1 - все ресурсы должны по максимуму кэшироваться.  В данном случае каждый вызов `toggleClass` будет провоцировать `querySelector`, что не самая дешевая операция.
2 - названия классов лучше хранить в переменных.

![js](https://user-images.githubusercontent.com/75975369/115955780-6603af80-a501-11eb-820e-0de7f8559ef5.jpg)

**Comment by mglknFSD** [comment]
Зачем ты хранишь минифицированные исходники библиотек в проекте? Их нельзя установить через npm?

![libs](https://user-images.githubusercontent.com/75975369/115955962-add70680-a502-11eb-8284-1eec5ed4d621.jpg)

**Comment by Rqik** [comment]
Вынес в переменные классы.
Везде где используются дом запросы поправил код чтобы элементы кэшировались и уже с ними продолжали работу.
Удалил минифицированные исходники подключил напрямую

**Comment by mglknFSD** [comment]
Вся бизнес логика должна быть в классах. 
[Все подключаемые библиотеки должны быть максимально абстрагированы от реализации проекта.](https://github.com/Rqik/FSD/issues/43)

![hs](https://user-images.githubusercontent.com/75975369/116789709-d342b200-aab8-11eb-988d-68f3f56301eb.jpg)
