### ISSUE TITLE
Plug-in libraries

### ISSUE THREAD

**Issue by mglknFSD** [Rqik/FSD#43]
Все подключаемые библиотеки должны быть максимально абстрагированы от реализации проекта. Т.е. они должны использоваться 'под капотом', но при этом не сильно влиять на код.
Т.е. если либы требуют подключения своих скриптов/стилей непосредственно - то для этого должна быть отдельная папка(для всех используемых либ), где будут лежат стили и скрипты этих либ.
А твои компоненты должны быть реализованы твоей архитектурой, но просто с использованием файлов либы.

В общем, range slider должен быть по минимум связан с либой которую ты используешь - все стили и скрипты из блока range-slider нужно будет вынести. 

Т е, например. ты хочешь подключить slider. Создаешь `libs/slider` в index.js ты пишешь класс Slider где описываешь инициализацию этого слайдера, slider.css - переопределяшь стили и т д. А в компоненте Slider ты подключаешь свою библиотеку. Нужно это что бы код твоего компонента не зависел от используемой библиотеки, и ты, в идеале, бы мог подключить другую библиотеку не меняя код самого компонента.

**Comment by Rqik** [comment]
А если слайдер с картинками требует определенную структуру. Pug файлы можно выносить в libs ? Или это касается только скриптов и стилей

**Comment by mglknFSD** [comment]
> А если слайдер с картинками требует определенную структуру. Pug файлы можно выносить в libs ? Или это касается только скриптов и стилей

Ну это очень странный слайдер, которому нужны картинки. Я бы выбрал другой. 
Все что нужно можно выносить в libs
